blank_issues_enabled: false
contact_links:
  - name: General Questions / Discussions
    url: https://github.com/Kanarath/Sock_Spy/discussions
    about: Ask general questions, propose ideas, or start a conversation here.
